### PR TITLE
Move the breaking news to spark

### PR DESCRIPTION
**Pull request by yifanlisc**
This PR does the followings:

* Change the input to Kafka
* Change the output to PubSub
* Create a LocalFileInput, which, together with BigQueryOutput, makes it easier to test the logic locally

### CODE REVIEW

**Comment by yifanlisc** [comment]
Assigned to @sandeepshresthasc 
CC @muthusc

**Comment by muthusc** [comment]
lgtm

**Comment by sandeepshresthasc** [comment]
lgtm

**Comment by yifanlisc** [comment]
Squash merge commit 5c17337d11c960dcbe264efc9f2b88cfe73f6910 created by [Whaler](https://chrome.google.com/webstore/detail/whaler/kjfaikbmbbkbnjjeiambmjchclpfkedf). :whale:

**Pull request closed without merging**
